name: PR continuous integration

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 # we don't need the history, just the latest commit - this breaks "last updated" doc pages though!
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
